### PR TITLE
Makefile fixed to SDCard get working

### PR DESCRIPTION
**Pull request by mazsola2k**
this change necessary, otherwise the SDCard part of the Makefile is not working

### CODE REVIEW

**Review by jrrk — COMMENTED** [review]
Your changes should not be necessary if cardmem.log is generated correctly. This procedure is part of the checking that the user didn’t specify the host hard disk by mistake, which would be disastrous. If your change works for you, great - stick with it, but I don’t want to remove the checking from the release version.

**Comment by mazsola2k** [comment]
I had to make this fix as per original version does not fill cardmemlog
file then after does not issue valid syntax commands in ubuntu 16.04. If
you can double check.

**Comment by jrrk** [comment]
I understand, but it worked for me previously. Please remove cardmem.log and make it again and capture the command sequence and resulting file, so I can comment.

**Comment by mazsola2k** [comment]
jrrk, here is a the full session log from a clean git checkout and with
high permission user "root", so should not be a problem of a not clean
environment or a permission issue.

*root@ubuntu:~# fdisk -l*
Disk /dev/sda: 100 GiB, 107374182400 bytes, 209715200 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x865d2999

Device     Boot     Start       End   Sectors  Size Id Type
/dev/sda1  *         2048 207714303 207712256   99G 83 Linux
/dev/sda2       207716350 209713151   1996802  975M  5 Extended
/dev/sda5       207716352 209713151   1996800  975M 82 Linux swap / Solaris


Disk /dev/sdb: 14.7 GiB, 15811477504 bytes, 30881792 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x5713046a

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1        2048 30881791 30879744 14.7G 83 Linux

root@ubuntu:/home/mazsola/test/lowrisc-quickstart# *make USB=sdb cleandisk
partition*
rm -f cardmem.log
Checking /dev/sdb
for i in `lsblk -P -o NAME,MOUNTPOINT | grep sdb | grep 'MOUNTPOINT="/' |
cut -d\" -f4`; do umount $i; done
Checking /dev/sdb
lsblk -P -o NAME|grep sdb | grep [1-9] && sudo partx -d /dev/sdb
NAME="sdb1"
sudo sh cardmem.sh /dev/sdb
cardmem.sh: 1: cardmem.sh: source: not found
Checking that no-one is using this disk right now ... OK

Disk /dev/sdb: 14.7 GiB, 15811477504 bytes, 30881792 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x5713046a

Old situation:

Device     Boot Start      End  Sectors  Size Id Type
/dev/sdb1        2048 30881791 30879744 14.7G 83 Linux

>>> Script header accepted.
>>> Script header accepted.
>>> Script header accepted.
>>> Created a new DOS disklabel with disk identifier 0xdeadbeef.
Created a new partition 1 of type 'W95 FAT32 (LBA)' and of size 32 MiB.
/dev/sdb2: Created a new partition 2 of type 'Linux' and of size 2 GiB.
/dev/sdb3: Created a new partition 3 of type 'Linux swap / Solaris' and of
size 512 MiB.
/dev/sdb4: Created a new partition 4 of type 'Linux' and of size 512 MiB.
All partitions used.

New situation:

Device     Boot   Start     End Sectors  Size Id Type
/dev/sdb1  *       2048   67582   65535   32M  c W95 FAT32 (LBA)
/dev/sdb2         67584 4261887 4194304    2G 83 Linux
/dev/sdb3       4261888 5310463 1048576  512M 82 Linux swap / Solaris
/dev/sdb4       5310464 6359039 1048576  512M 83 Linux

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
Checking that no-one is using this disk right now ... OK

Disk /dev/sdb: 14.7 GiB, 15811477504 bytes, 30881792 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xdeadbeef

Old situation:

Device     Boot   Start     End Sectors  Size Id Type
/dev/sdb1  *       2048   67582   65535   32M  c W95 FAT32 (LBA)
/dev/sdb2         67584 4261887 4194304    2G 83 Linux
/dev/sdb3       4261888 5310463 1048576  512M 82 Linux swap / Solaris
/dev/sdb4       5310464 6359039 1048576  512M 83 Linux

/dev/sdb4:
New situation:

Device     Boot   Start      End  Sectors  Size Id Type
/dev/sdb1  *       2048    67582    65535   32M  c W95 FAT32 (LBA)
/dev/sdb2         67584  4261887  4194304    2G 83 Linux
/dev/sdb3       4261888  5310463  1048576  512M 82 Linux swap / Solaris
/dev/sdb4       5310464 30881791 25571328 12.2G 83 Linux

The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
sleep 2
lsblk -P -o NAME,PARTUUID | grep sdb | grep deadbeef | tail -4 > cardmem.log

root@ubuntu:/home/mazsola/test/lowrisc-quickstart# *make USB=sdb mkfs
fatdisk extdisk*
sudo mkfs -t msdos /dev/`grep deadbeef-01 cardmem.log | cut -d\" -f2`
mkfs.fat 3.0.28 (2015-05-16)
mkfs.msdos: unable to open /dev/: Is a directory
Makefile:109: recipe for target 'mkfs' failed
make: *** [mkfs] Error 1



jrrk <notifications@github.com> ezt írta (időpont: 2019. szept. 27., P,
8:41):

**Comment by jrrk** [comment]
Ubuntu by default uses dash as it’s default shell /bin/sh rather than bash. This breaks all sorts of scripts including the source command as shown above. Either fix your shell globally or explicitly call up bash instead of sh in the above flow.

**Comment by jrrk** [comment]
Did the change to /bin/bash help ? If so please submit a new pull request with the simplified change. Meanwhile I am closing this one as it seems to be unsafe.

**Pull request closed without merging**
